import jwt
from flask import current_app


def encode(payload):
    """
    The `encode` function encodes a payload using JWT with a specified secret and algorithm.
    
    :param payload: The `payload` parameter in the `encode` function is typically a dictionary
    containing the data that you want to encode into a JSON Web Token (JWT). This data can include
    information such as user ID, username, expiration time, and any other relevant information that you
    want to securely transmit and verify
    :return: The `encode` function is returning a JSON Web Token (JWT) encoded with the given payload
    using the HS256 algorithm and the JWT_SECRET from the current_app's configuration.
    """
    return jwt.encode(payload, current_app.config['JWT_SECRET'], algorithm='HS256')

def decode(token):
    """
    The `decode` function decodes a JWT token using a specified secret key and algorithm.
    
    :param token: The `token` parameter in the `decode` function is typically a string that represents a
    JSON Web Token (JWT). This token is generated by a server and contains encoded information that can
    be decoded using the appropriate key
    :return: The `decode` function is returning the decoded content of the JWT token using the
    `jwt.decode` method with the provided token, JWT secret key from the current app configuration, and
    the specified algorithm 'HS256'.
    """
    return jwt.decode(token, current_app.config['JWT_SECRET'], algorithms=['HS256'])
