version: '3'

services:

  internship_db:
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - instance/config.py
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
    driver: local